### PR TITLE
Improve initialization to avoid skipping modifying DOM nodes on time

### PR DESCRIPTION
**Pull request by jdapena**
Block execution of the content script while we fetch the extension selector

### CODE REVIEW

**Comment by jasonwilliams** [comment]
Does this actually work? It looks like it would fall into the same problem we had before; while it fetches the choice the browser has time to paint and it will miss some DOM nodes. This only blocks the registration not the browser painting

**Comment by jdapena** [comment]
At least for the known cases it works. But I am not sure this is going to be 100% effective. When scripts are found, the earliest possible, if code starts to be executed this way, it is actually going to block the JS main loop, so it makes any other DOM construction less likely to happen. In theory to the point there would not be even body loaded.

But that should be easy to verify, just checking how much of the DOM is available when we register the mutation observer. I will investigate that.

**Comment by jdapena** [comment]
I've been adding a breakpoint to when the method is called, and I can see DOM is barely built (part of the HEAD and usually body is not there, or there but empty).

So I guess it may indeed happen that in case of very basic DOM it gets parsed and even painted before processing the script, but it is not going to happen often. In any case this approach makes it more likely to be selected on time.

Though, there is obviously a problem here: we are actually delaying the initialization of the web page (and so, delaying parsing, painting), and that has impact on the measures. But, for the purpose of demoing container timing it should still be OK.

**Comment by jasonwilliams** [comment]
> At least for the known cases it works. But I am not sure this is going to be 100% effective. When scripts are found, the earliest possible, if code starts to be executed this way, it is actually going to block the JS main loop, so it makes any other DOM construction less likely to happen. In theory to the point there would not be even body loaded.
> 
> But that should be easy to verify, just checking how much of the DOM is available when we register the mutation observer. I will investigate that.

If the JS is synchronous then yes, but in this case we have a promise which wraps a callback for the extension value. While we wait for the callback to fire the browser is going to skip passed this script and paint. Only the JS in the script blocks but not the main event loop

**Comment by jdapena** [comment]
Closing pull request as the repository is deprecated.

**Pull request closed without merging**
